# GitHub Actions - CI for Go with just builders and tests.  Use cover.yml and linters.yml for coverage and linting.
name: ci
on: [push]
jobs:

  # Test on various OS with default Go version. Specifying Go version causes too much slowdown as of January 2020.
  tests:
    name: Test on ${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Get dependencies
      run: go get -v -t -d ./...
    - name: Build project
      run: go build ./...
    - name: Run tests
      run: |
        go version
        go test -short -race -v ./...
